'use strict';

import { micro, dedupeByText } from './helpers.mjs';

/** Year-scoped knobs for template expansion */
const ERA_KNOBS = {
  2006: { game: '魔兽世界', pay: '50', rent: '800', app: 'QQ空间', meme: '很黄很暴力', show: '超级女声' },
  2007: { game: '天龙八部', pay: '80', rent: '900', app: '人人网', meme: '囧', show: '快乐男声' },
  2008: { game: '地下城与勇士', pay: '100', rent: '1000', app: '开心网', meme: '很傻很天真', show: '北京奥运' },
  2009: { game: '植物大战僵尸', pay: '120', rent: '1100', app: '新浪微博', meme: '贾君鹏', show: '潜伏' },
  2010: { game: '英雄联盟', pay: '150', rent: '1200', app: '微信', meme: '给力', show: '非诚勿扰' },
  2011: { game: '王者荣耀前身时期', pay: '180', rent: '1400', app: '微信', meme: 'Hold住', show: '甄嬛传' },
  2012: { game: '阴阳师未起', pay: '200', rent: '1600', app: '微信朋友圈', meme: '元芳你怎么看', show: '中国好声音' },
  2013: { game: '剑网3', pay: '220', rent: '1800', app: '支付宝', meme: '土豪我们做朋友', show: '爸爸去哪儿' },
  2014: { game: '炉石传说', pay: '250', rent: '2000', app: '滴滴打车', meme: '且行且珍惜', show: '奔跑吧兄弟' },
  2015: { game: '王者荣耀内测', pay: '280', rent: '2200', app: '美团外卖', meme: '世界那么大', show: '琅琊榜' },
  2016: { game: 'Pokemon GO', pay: '300', rent: '2500', app: '抖音', meme: '葛优躺', show: '三生三世' },
  2017: { game: '吃鸡手游', pay: '350', rent: '2800', app: '抖音', meme: '佛系', show: '人民的名义' },
  2018: { game: '绝地求生', pay: '400', rent: '3000', app: '拼多多', meme: '确认过眼神', show: '我不是药神' },
  2019: { game: '原神预告期', pay: '450', rent: '3200', app: 'B站', meme: '我太难了', show: '哪吒' },
  2020: { game: '原神', pay: '500', rent: '3400', app: '钉钉', meme: '夺笋', show: '隐秘的角落' },
  2021: { game: '原神', pay: '520', rent: '3600', app: '小红书', meme: 'YYDS', show: '长津湖' },
  2022: { game: '羊了个羊', pay: '550', rent: '3800', app: '微信', meme: '退退退', show: '狂飙' },
  2023: { game: '崩坏星穹铁道', pay: '580', rent: '4000', app: 'ChatGPT', meme: '特种兵式旅游', show: '漫长的季节' },
  2024: { game: '黑神话悟空', pay: '600', rent: '4200', app: 'DeepSeek', meme: 'city不city', show: '庆余年2' },
  2025: { game: '黑神话DLC', pay: '620', rent: '4300', app: 'AI助手', meme: '班味', show: '哪吒2' },
  2026: { game: 'AI原生游戏', pay: '650', rent: '4500', app: 'Agent应用', meme: '待更新', show: '待更新' }
};

function knobs(year) {
  return ERA_KNOBS[year] || ERA_KNOBS[2018];
}

export function expandMicroEvents(year, curated = []) {
  const k = knobs(year);
  const y = String(year);
  const generated = [
    micro('family', `春节回家，亲戚追问「${y}年打算考研还是工作」`, 1.1, true, 'low', ['spring', 'pressure']),
    micro('family', '母亲把相亲对象照片发到家族群，你选择已读不回', 0.9, true, 'low', ['marriage']),
    micro('family', '父亲在饭桌上说「别人家孩子已经买房了」', 1.0, true, 'low', ['housing']),
    micro('family', '奶奶住院，你在医院走廊改简历', 1.2, true, 'medium', ['health']),
    micro('school', `室友通宵打${k.game}，你戴着耳塞刷题到两点`, 0.8, false, 'low', ['dorm']),
    micro('school', '四级成绩公布，你差一分没过', 1.0, true, 'low', ['exam']),
    micro('school', '社团招新，你犹豫要不要竞选部长', 0.7, false, 'low', ['club']),
    micro('school', '毕业论文选题被导师打回三次', 1.1, true, 'low', ['thesis']),
    micro('school', '实习答辩当天，你发现自己PPT页码错了', 0.6, false, 'low', ['intern']),
    micro('work', `实习工资${k.pay}元/天，午餐只敢吃食堂最便宜的窗口`, 1.0, false, 'low', ['intern']),
    micro('work', '部门群里@全体成员，你假装没看见直到被点名', 0.9, false, 'low', ['office']),
    micro('work', '996讨论上热搜，你公司发邮件强调「奋斗者文化」', 1.2, true, 'medium', ['996']),
    micro('work', '裁员名单流传，工位空了一半', 1.3, true, 'medium', ['layoff']),
    micro('work', '领导说「年轻人要多承担」，你接下不属于你的项目', 1.0, true, 'low', ['overwork']),
    micro('romance', '前任在朋友圈晒结婚照，你划过去又划回来', 0.9, true, 'low', ['breakup']),
    micro('romance', '相亲对象问「你有房吗」，你笑了一下没回答', 1.0, true, 'low', ['dating']),
    micro('romance', '异地恋视频时对方说「我们冷静一下」', 1.1, true, 'medium', ['distance']),
    micro('money', `合租房东通知：${y}年涨租200元，每月${k.rent}元`, 1.1, true, 'low', ['rent']),
    micro('money', '花呗账单日，你先把最低还款还上', 0.9, false, 'low', ['debt']),
    micro('money', '基金绿了一周，你发誓再也不看账户', 0.8, false, 'low', ['invest']),
    micro('money', '工资到账短信和房贷扣款短信几乎同时到达', 1.2, true, 'low', ['mortgage']),
    micro('health', '体检报告「轻度脂肪肝」，你买了健身卡却只去了一次', 0.7, false, 'low', ['health']),
    micro('health', '连续熬夜后心悸，你去搜「是不是要猝死了」', 1.0, true, 'medium', ['burnout']),
    micro('neighborhood', '地铁新线开通，通勤缩短20分钟', 0.6, false, 'low', ['transit']),
    micro('neighborhood', '楼下商铺换成连锁奶茶，常去的小馆关门了', 0.5, false, 'low', ['gentrification']),
    micro('neighborhood', '小区群发通知：垃圾分类督导员上岗', 0.5, false, 'low', ['policy']),
    micro('digital', `${k.app}推送「${k.meme}」相关热搜，你转发又删除`, 0.7, false, 'low', ['meme']),
    micro('digital', `追的综艺${k.show}更新，你熬夜看完第二天迟到`, 0.6, false, 'low', ['entertainment']),
    micro('digital', '微博热搜爆了一个你所在行业的丑闻', 1.0, false, 'medium', ['news']),
    micro('digital', '群聊里同学晒offer，你默默把聊天设成免打扰', 1.0, true, 'low', ['peer']),
    micro('policy_touch', '落户政策微调，你查攻略到凌晨', 0.9, true, 'low', ['hukou']),
    micro('policy_touch', '考研报名系统卡顿，你刷新了一小时', 0.8, false, 'low', ['exam']),
    micro('school', '教资/公考培训班传单塞满宿舍门缝', 0.7, false, 'low', ['exam']),
    micro('work', '面试被问「能接受出差吗」，你知道这意味着全年飞', 0.9, true, 'low', ['job']),
    micro('work', '同事离职请客，饭桌上说「行业不行了」', 1.0, true, 'low', ['industry']),
    micro('family', '妹妹高考，家人把关注全转过去，你突然松一口气', 0.8, false, 'low', ['sibling']),
    micro('money', '双十一购物车删了又加，最后只买了必需品', 0.6, false, 'low', ['shopping']),
    micro('romance', 'Crush给你点了外卖，备注写「加油」', 0.7, false, 'low', ['crush']),
    micro('health', '牙疼拖了三周，终于预约到周末号源', 0.5, false, 'low', ['dental']),
    micro('neighborhood', '暴雨淹了小区门口，你拖鞋趟水上班', 0.9, true, 'medium', ['weather']),
    micro('digital', '短视频刷到「同龄人已经年入百万」', 1.1, true, 'low', ['anxiety']),
    micro('school', '图书馆占座大战，你六点去排队', 0.6, false, 'low', ['study']),
    micro('work', '远程办公第一天，你穿着睡衣开摄像头', 0.7, false, 'low', ['wfh']),
    micro('family', '视频通话里看到父母白发多了，你转开话题', 1.0, true, 'low', ['aging']),
    micro('money', '兼职翻译2000字，稿费80块', 0.6, false, 'low', ['sidejob']),
    micro('policy_touch', '居住证续签窗口排队三小时', 0.7, false, 'low', ['bureaucracy']),
    micro('school', '同学出国读书，散伙饭上大家都喝多', 0.8, true, 'low', ['farewell']),
    micro('work', '年会抽奖没中，安慰奖是一盒月饼', 0.4, false, 'low', ['office']),
    micro('digital', '游戏新赛季更新，你请假的理由编得很烂', 0.5, false, 'low', ['game']),
    micro('romance', '暧昧对象已读不回48小时', 0.9, true, 'low', ['ghosting']),
    micro('health', '心理咨询预约排到两周后', 1.0, true, 'medium', ['mental']),
    micro('neighborhood', '快递柜超时收费，你和邻居一起投诉', 0.5, false, 'low', ['daily']),
    micro('family', '家里让你考公务员「稳定」，你口头答应', 1.0, true, 'low', ['civil_service']),
    micro('work', '工牌刷不进新门禁，保安说系统升级', 0.4, false, 'low', ['office']),
    micro('money', '共享单车月卡涨价，你改骑地铁', 0.3, false, 'low', ['daily']),
    micro('school', '实验数据跑飞了，你在实验室通宵重跑', 0.9, true, 'low', ['lab']),
    micro('digital', '朋友圈有人晒证，你点赞后立刻划走', 0.7, false, 'low', ['social']),
    micro('policy_touch', '个税App提醒专项附加扣除', 0.4, false, 'low', ['tax']),
    micro('work', '客户改需求第五版，你微笑说「好的收到」', 1.0, true, 'low', ['client']),
    micro('family', '过年红包金额被 cousin 比较，你笑得很僵', 0.6, false, 'low', ['spring']),
    micro('health', '体检排队空腹到中午，低血糖手抖', 0.7, false, 'low', ['health']),
    micro('romance', '分手后的歌单随机播到那一首', 0.8, true, 'low', ['music']),
    micro('neighborhood', '物业通知停水停电，你提前接了三盆水', 0.5, false, 'low', ['utility']),
    micro('money', '信用卡分期广告弹窗，你点了关闭', 0.5, false, 'low', ['debt']),
    micro('digital', '群文件「就业形势分析.pdf」下载了没打开', 0.6, false, 'low', ['career']),
    micro('school', '选课系统崩溃，你捡漏一门冷门课', 0.5, false, 'low', ['course']),
    micro('work', '电梯里听见HR聊「优化」，你楼层到了', 1.2, true, 'medium', ['layoff']),
    micro('family', '父母学会用视频通话，每次先问「吃饭了吗」', 0.5, false, 'low', ['parent']),
    micro('policy_touch', '核酸/健康码政策变动，你截图保存攻略', year <= 2022 ? 1.2 : 0.3, year <= 2022, year <= 2022 ? 'high' : 'low', ['covid']),
    micro('digital', year >= 2020 ? '居家办公Zoom会议，你忘关麦克风吐槽老板' : 'QQ群文件病毒谣言，你转发辟谣链接', 0.8, false, 'low', ['internet']),
    micro('work', year >= 2018 ? '面试被问「35岁怎么办」，你愣了一秒' : '第一份工资到手，你请室友吃了顿好的', year >= 2018 ? 1.0 : 0.8, year >= 2018, 'low', ['career']),
    micro('money', year >= 2015 ? 'P2P暴雷新闻出来，你查自己的理财App' : '存折去银行排队，前面大爷聊房价', year >= 2015 ? 1.1 : 0.7, year >= 2015, 'medium', ['finance']),
    micro('school', year === 2008 ? '地震捐款，你掏空饭卡捐了50块' : '期末周占座贴条「考研勿扰」', year === 2008 ? 1.3 : 0.7, year === 2008, year === 2008 ? 'high' : 'low', ['society']),
    micro('digital', year === 2022 ? '封控期间团购接龙，你负责统计楼栋需求' : '论坛晒工资条被HR约谈', year >= 2020 ? 1.2 : 0.6, year >= 2020, year >= 2020 ? 'high' : 'low', ['covid']),
    micro('family', year === 2020 ? '春节没能回家，视频里妈妈转头擦眼睛' : '家族群转发养生谣言，你选择不回复', year === 2020 ? 1.4 : 0.6, year === 2020, year === 2020 ? 'high' : 'low', ['spring']),
    micro('work', year === 2023 ? 'ChatGPT帮你写周报，你改了三版才敢交' : '打印机卡纸，全办公室等你修', year >= 2023 ? 1.0 : 0.5, false, 'low', ['ai']),
    micro('school', year === 2024 ? '考研国家线公布，你刷榜刷到手机发烫' : '选修课签到二维码，室友让你代扫', 0.9, true, 'low', ['exam']),
    micro('money', year === 2024 ? '黄金金价新高，妈妈让你别跟风买' : '食堂涨价5毛，朋友圈骂了一天', 0.7, false, 'low', ['inflation']),
    micro('digital', year === 2025 ? 'DeepSeek上热搜，你让AI帮你改简历' : '博客园/知乎长文收藏了从未读完', year >= 2025 ? 1.0 : 0.6, false, 'low', ['ai']),
    micro('neighborhood', year === 2008 ? '奥运期间地铁安检变严，你提前一小时出门' : '共享单车颜色换了一批', year === 2008 ? 1.0 : 0.4, false, year === 2008 ? 'medium' : 'low', ['olympics']),
    micro('health', year === 2020 ? '囤口罩和酒精，快递堆满玄关' : '换季过敏，药店断货一种鼻喷', year === 2020 ? 1.3 : 0.6, year === 2020, year === 2020 ? 'high' : 'low', ['covid']),
    micro('policy_touch', year === 2016 ? '二胎政策放开，亲戚问你们家打算吗' : '居住证积分政策解读文章收藏夹吃灰', year === 2016 ? 0.9 : 0.5, false, 'low', ['policy']),
    micro('work', year === 2019 ? '互联网寒冬，内推码突然没人要了' : '实习转正答辩，PPT最后一页写「谢谢」', year === 2019 ? 1.2 : 0.8, year === 2019, 'medium', ['tech']),
    micro('school', year === 2017 ? '双一流名单公布，你查母校在不在' : '占座神器「占座猴」在二手群转让', 0.8, false, 'low', ['education']),
    micro('family', year === 2015 ? '全面二孩话题上春晚，年夜饭被追问' : '父亲学会微信转账，每次多转50让你收下', 0.7, false, 'low', ['policy']),
    micro('digital', year === 2016 ? '直播打赏新闻，你第一次看直播到半夜' : 'B站弹幕玩梗，你跟不上缩写', year === 2016 ? 0.8 : 0.5, false, 'low', ['livestream']),
    micro('money', year === 2021 ? '教培双减，你报的课退款排期三个月' : 'ATM取现限额，你跑了两家银行', year === 2021 ? 1.2 : 0.6, year === 2021, 'medium', ['education']),
    micro('work', year === 2022 ? '居家办公考勤App要拍照，你在被窝打卡' : '团建强制爬山，你膝盖疼但不敢请假', year >= 2020 ? 1.0 : 0.7, false, 'low', ['wfh']),
    micro('romance', year === 2023 ? '约会对象说「感觉你不够松弛」' : '情人节外卖鲜花迟到，你仍说没关系', 0.8, true, 'low', ['dating']),
    micro('school', year === 2025 ? 'AI查重系统升级，你参考文献格式改一夜' : '实验室师兄留校读博，你问「值得吗」', year >= 2024 ? 1.0 : 0.7, false, 'low', ['ai']),
    micro('neighborhood', year === 2026 ? '人形机器人进小区试点，老人围观拍照' : '旧改公告贴单元门，邻居讨论补偿方案', year >= 2026 ? 0.9 : 0.7, false, 'low', ['urban']),
    micro('health', year === 2026 ? '体检多了AI辅助筛查项目，报告多三页' : '瑜伽课团购券过期前最后一天去', year >= 2025 ? 0.6 : 0.4, false, 'low', ['health'])
  ];

  return dedupeByText([...curated, ...generated]);
}
